'use strict';

export const HELLO_WORLD = 'HELLO_WORLD';
export const REDUX_RESET_STATE = 'REDUX_RESET_STATE';

//ADMIN AUTH
export const ADMIN_GET_ALL_MENU = 'GET_ALL_MENU';
export const ADMIN_GET_ALL_MENU_SUCCESS = 'GET_ALL_MENU_SUCCESS';
export const ADMIN_UPDATE_NAVPATH = 'UPDATE_NAVPATH';
// ADMIN LOGIN
export const ADMIN_FETCH_PROFILE_PENDING = 'FETCH_PROFILE_PENDING';
export const ADMIN_FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const ADMIN_LOGIN_PENDING = 'LOGIN_PENDING';
export const ADMIN_LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ADMIN_LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// auth constants
export const AUTH_UPDATE_REGISTER_FORM_FIELD = 'AUTH_UPDATE_REGISTER_FORM_FIELD';
export const AUTH_SUBMIT_REGISTER_FORM = 'AUTH_SUBMIT_REGISTER_FORM';
export const AUTH_INVALIDATE_REGISTER_FORM = 'AUTH_INVALIDATE_REGISTER_FORM';
export const AUTH_RESET_REGISTER_FORM_FIELDS = 'AUTH_RESET_REGISTER_FORM_FIELDS';

export const AUTH_UPDATE_USER_DATA = 'AUTH_UPDATE_USER_DATA';
export const AUTH_RESET_USER_DATA = 'AUTH_RESET_USER_DATA';
export const AUTH_UPDATE_USER_FIELD = 'AUTH_UPDATE_USER_FIELD';

export const AUTH_UPDATE_LOGIN_FORM_FIELD = 'AUTH_UPDATE_LOGIN_FORM_FIELD';
export const AUTH_SUBMIT_LOGIN_FORM = 'AUTH_SUBMIT_LOGIN_FORM';
export const AUTH_INVALIDATE_LOGIN_FORM = 'AUTH_INVALIDATE_LOGIN_FORM';
export const AUTH_RESET_LOGIN_FORM_FIELDS = 'AUTH_RESET_LOGIN_FORM_FIELDS';

export const AUTH_SUBMIT_RESET_PASSWORD_FORM = 'AUTH_SUBMIT_RESET_PASSWORD_FORM';
export const AUTH_UPDATE_RESET_PASSWORD_STATUS_FIELD = 'AUTH_UPDATE_RESET_PASSWORD_STATUS_FIELD';
export const AUTH_INVALIDATE_RESET_PASSWORD_FORM = 'AUTH_INVALIDATE_RESET_PASSWORD_FORM';

// app constants
export const APP_CONFIG_TOGGLE_ASIDE = 'APP_CONFIG_TOGGLE_ASIDE';
export const USER_PROFILE_LOADED = 'USER_PROFILE_LOADED';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_UPDATE_PROFILE_FIELD = 'USER_UPDATE_PROFILE_FIELD';
export const USER_DELETE_PROFILE_FIELD = 'USER_DELETE_PROFILE_FIELD';
export const SUBMIT_NEW_TUTS_MODEL_OPEN = 'SUBMIT_NEW_TUTS_MODEL';
export const SUBMIT_NEW_TUTS_MODEL_CLOSE = 'SUBMIT_NEW_TUTS_MODEL_CLOSE';
export const COURSE_LOAD = 'COURSE_LOAD';
export const SELECTED_COURSE_TUTS_SUCCESS = 'SELECTED_COURSE_TUTS_SUCCESS';
export const SUBMIT_COURSE_SUCCESS = 'SUBMIT_COURSE_SUCCESS';
export const COURSE_LOAD_SUCCESS = 'COURSE_LOAD_SUCCESS';


export const TRAINING_LOAD = 'TRAINING_LOAD'
export const TRAINING_LOAD_SUCCESS = 'TRAINING_LOAD_SUCCESS'
export const SELECTED_TRAINING_SUCCESS = 'SELECTED_TRAINING_SUCCESS'
export const SUBMIT_TRAINING_SUCCESS = 'SUBMIT_TRAINING_SUCCESS'
export const SUBMIT_NEW_TRAINING_MODEL_OPEN = 'SUBMIT_NEW_TRAINING_MODEL_OPEN'
export const SUBMIT_NEW_TRAINING_MODEL_CLOSE = 'SUBMIT_NEW_TRAINING_MODEL_CLOSE'
export const FETCH_TRAINING_SUCCESS ='FETCH_TRAINING_SUCCESS';